#!/usr/bin/env python3
"""Convert the Bad Apple!! shadow-art PV into frames for the 12x16 LED matrix.

Input: numbered frame images (frame-0001.jpg ...; the 30 fps set from
https://github.com/irqd/bad-apple works). Writes
keyboards/bastardkb/dilemma/3x5_3_trackball/keymaps/ykz89/badapple_data.h. Needs Pillow.

    tools/led-matrix-sim/badapple.py <frames dir> [--fps 15]

Encoding: a frame is runs over its 192 cells, row-major from the top-left;
each run is one byte, (level << 6) | (length - 1), level 0..3, length 1..64.
"""
import argparse
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'keyboards/bastardkb/dilemma/3x5_3_trackball/keymaps/ykz89/badapple_data.h'
COLS, ROWS, SRC_FPS = 12, 16, 30


def frame_levels(path):
    im = Image.open(path).convert('L')
    w, h = im.size
    cw = h * COLS // ROWS                      # centre slice with the panel's aspect
    im = im.crop(((w - cw) // 2, 0, (w - cw) // 2 + cw, h)).resize((COLS, ROWS), Image.BOX)
    # Four levels: thresholds at a quarter, half and three quarters, so a cell
    # that is mostly white reads as white and edges get the in-between greys.
    return [min(3, v * 4 // 256) for v in im.getdata()]


def rle(levels):
    out, i = [], 0
    while i < len(levels):
        n = 1
        while i + n < len(levels) and levels[i + n] == levels[i] and n < 64:
            n += 1
        out.append(levels[i] << 6 | (n - 1))
        i += n
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('frames', type=Path)
    ap.add_argument('--fps', type=int, default=15)
    args = ap.parse_args()

    files = sorted(args.frames.glob('frame-*.jpg'))
    if not files:
        sys.exit(f'no frame-*.jpg in {args.frames}')
    step = SRC_FPS // args.fps
    data, frames = [], 0
    for f in files[::step]:
        data += rle(frame_levels(f))
        frames += 1

    rows = [', '.join(f'0x{b:02X}' for b in data[i:i + 24]) for i in range(0, len(data), 24)]
    OUT.write_text(
        f'// Generated by tools/led-matrix-sim/badapple.py from the Bad Apple!! shadow-art PV\n'
        f'// ({len(files)} frames at {SRC_FPS} fps). Do not edit; rerun the script instead.\n'
        f'// {frames} frames, {COLS}x{ROWS}, 4 grey levels, {args.fps} fps, run-length encoded:\n'
        f'// each byte is (level << 6) | (run length - 1), row-major from the top-left.\n\n'
        f'#pragma once\n\n#include <stdint.h>\n\n'
        f'#define BKLM_BADAPPLE_FRAMES {frames}\n#define BKLM_BADAPPLE_FPS {args.fps}\n\n'
        f'static const uint8_t bklm_badapple_rle[{len(data)}] = {{\n    ' + ',\n    '.join(rows) + ',\n};\n')
    print(f'{frames} frames, {len(data)} bytes ({len(data) / frames:.1f}/frame, raw 2-bit would be {frames * 48}) -> {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
