// Copyright 2026 Quentin LEBASTARD <bstkbd@gmail.com>
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include <stdint.h>

/* Pictogram well. Origin is (panel - well) / 2 so a size change keeps it centered. */
#define LED_MATRIX_ICON_W 8
#define LED_MATRIX_ICON_H 12

/*
 * Indexed color, not raw RGB: a bitmap says "cyan" instead of {62,207,255}.
 * Recolor the panel by editing one palette slot. Enum order is palette order.
 */
enum {
    LED_MATRIX_PIX_OFF = 0,
    LED_MATRIX_PIX_CYAN,
    LED_MATRIX_PIX_WHITE,
    LED_MATRIX_PIX_GREEN,
    LED_MATRIX_PIX_YELLOW,
    LED_MATRIX_PIX_ORANGE,
    LED_MATRIX_PIX_COUNT
};

typedef struct {
    uint8_t r;
    uint8_t g;
    uint8_t b;
} led_matrix_icon_rgb_t;

/* Row 0 is the top of the well so the arrays read like the picture. */
typedef struct {
    uint8_t pixel[LED_MATRIX_ICON_H][LED_MATRIX_ICON_W];
} led_matrix_icon_t;

/*
 * Palette and bitmaps are compiled into whichever .c defines
 * LED_MATRIX_ICONS_DEFINE before the include. Without the guard, every
 * includer would get its own copy in flash.
 */
#ifdef LED_MATRIX_ICONS_DEFINE

static const led_matrix_icon_rgb_t led_matrix_icon_palette[LED_MATRIX_PIX_COUNT] = {
    {0, 0, 0},       /* OFF    */
    {62, 207, 255},  /* CYAN   #3ecfff */
    {244, 247, 255}, /* WHITE  #f4f7ff */
    {61, 255, 154},  /* GREEN  #3dff9a */
    {255, 229, 102}, /* YELLOW #ffe566 */
    {255, 138, 61},  /* ORANGE #ff8a3d */
};

/* Same tokens as the enum; short names keep the wells scannable. */
#define PIX_OFF    LED_MATRIX_PIX_OFF
#define PIX_CYAN   LED_MATRIX_PIX_CYAN
#define PIX_WHITE  LED_MATRIX_PIX_WHITE
#define PIX_GREEN  LED_MATRIX_PIX_GREEN
#define PIX_YELLOW LED_MATRIX_PIX_YELLOW
#define PIX_ORANGE LED_MATRIX_PIX_ORANGE

static const led_matrix_icon_t led_matrix_icon_sniping = {{ /* cyan reticle */
    {PIX_OFF, PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_CYAN, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_CYAN},
    {PIX_CYAN, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_CYAN},
    {PIX_CYAN, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_CYAN},
    {PIX_CYAN, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_CYAN},
    {PIX_CYAN, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_CYAN},
    {PIX_CYAN, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_CYAN},
    {PIX_CYAN, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_CYAN},
    {PIX_CYAN, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_CYAN},
    {PIX_OFF, PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF},
}};

static const led_matrix_icon_t led_matrix_icon_dragscroll = {{ /* scrollbar */
    {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_GREEN, PIX_GREEN, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_GREEN, PIX_GREEN, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_GREEN, PIX_GREEN, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_GREEN, PIX_GREEN, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
}};

static const led_matrix_icon_t led_matrix_icon_cursor = {{ /* serif I */
    {PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF},
    {PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF},
    {PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF},
}};

static const led_matrix_icon_t led_matrix_icon_brightness = {{ /* sun disc */
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF},
    {PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
}};

static const led_matrix_icon_t led_matrix_icon_zoom = {{ /* magnifier */
    {PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF},
    {PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_ORANGE, PIX_ORANGE, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_ORANGE, PIX_ORANGE, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_ORANGE, PIX_ORANGE},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_ORANGE},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
}};

static const led_matrix_icon_t led_matrix_icon_volume = {{ /* level bars */
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
}};

static const led_matrix_icon_t led_matrix_icon_tab_switch = {{ /* overlapping windows */
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_OFF},
    {PIX_OFF, PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
    {PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_OFF},
    {PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
}};

static const led_matrix_icon_t led_matrix_icon_history = {{ /* clock */
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_OFF},
    {PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_YELLOW},
    {PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_YELLOW},
    {PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW},
    {PIX_OFF, PIX_YELLOW, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_YELLOW, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
}};

/* Stacked with a 1-row gap so C and the digit read as two glyphs. */
#define LED_MATRIX_ICON_CUSTOM_LETTER_H 6
#define LED_MATRIX_ICON_CUSTOM_DIGIT_H  5

static const uint8_t led_matrix_icon_custom_letter[LED_MATRIX_ICON_CUSTOM_LETTER_H][LED_MATRIX_ICON_W] = { /* C */
    {PIX_OFF, PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_OFF},
    {PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
    {PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_OFF},
    {PIX_OFF, PIX_OFF, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_CYAN, PIX_OFF, PIX_OFF},
};

/* Index 0 is digit 1; the composer subtracts the first custom-mode id. */
static const uint8_t led_matrix_icon_custom_digit[5][LED_MATRIX_ICON_CUSTOM_DIGIT_H][LED_MATRIX_ICON_W] = {
    {
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF, PIX_OFF},
    },
    {
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
    },
    {
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
    },
    {
        {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF},
    },
    {
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_OFF, PIX_WHITE, PIX_OFF},
        {PIX_OFF, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_WHITE, PIX_OFF},
    },
};

#undef PIX_OFF
#undef PIX_CYAN
#undef PIX_WHITE
#undef PIX_GREEN
#undef PIX_YELLOW
#undef PIX_ORANGE

#endif /* LED_MATRIX_ICONS_DEFINE */