SRC += led_matrix_display.c
SRC += led_matrix_pointer.c
SRC += led_matrix_layers.c
SRC += led_matrix_mods.c
SRC += led_matrix_duck.c
# ykz89: trackball animations
SRC += led_matrix_motion.c
SRC += led_matrix_motion_bands.c
SRC += led_matrix_motion_comet.c
SRC += led_matrix_motion_sparks.c
SRC += led_matrix_motion_stars.c
SRC += led_matrix_motion_ball.c
SRC += led_matrix_motion_warp.c
SRC += led_matrix_motion_fireworks.c
SRC += led_matrix_motion_fireflies.c
SRC += led_matrix_motion_sand.c
SRC += led_matrix_motion_ocean.c
SRC += led_matrix_motion_water.c
SRC += led_matrix_motion_car.c
SRC += led_matrix_motion_asteroids.c
SRC += led_matrix_motion_matrix.c
SRC += led_matrix_motion_tetris.c
SRC += led_matrix_motion_badapple.c
SRC += led_matrix_layer_anims.c # ykz89: an animation per held layer
